site_name: xTrace Tickets
theme:
  name: material
  language: ko

plugins:
  - search
  - awesome-pages      # ğŸ“Œ ìë™ ë„¤ë¹„ê²Œì´ì…˜ í”ŒëŸ¬ê·¸ì¸

nav:
  - Home: index.md
  - Tickets: tickets/  # tickets í´ë” ì „ì²´ë¥¼ ìë™ íƒìƒ‰
